### ISSUE TITLE
Incompatibility with Random Things Rainshield

### ISSUE THREAD

**Issue by lumien231** [micdoodle8/MicdoodleCore#13]
In your Class Transformer you seem to completely replace the Rain Particle Logic [here](https://github.com/micdoodle8/MicdoodleCore/blob/cca937b0104e97251d260e36ff987c80b6516ce5/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L912-L935), would it be possible for you to let the vanilla code run when you don't have to change anything about the rain? I [also](https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/asm/ClassTransformer.java#L1551-L1577) change that method so my code isn't run with Galacticraft installed.

**Comment by radfast** [comment]
Fixed in code.  This fix will be included in our next published build 176, in the next couple of days.
