### ISSUE TITLE
Possible ticking entity crash with interaction between RFTools and galacticraft core

### ISSUE THREAD

**Issue by OmegaCenti** [micdoodle8/MicdoodleCore#6]
A user walking around with a modular storage tablet from Rftools causes the following hard crash > reports:

https://gist.github.com/OmegaCenti/98c6398a14cc02c67aa4bda4af1d612a

McJty/rftools/#475 and McJty/rftools/#503

**Comment by OmegaCenti** [comment]
This might help McJty find this thread at well, so pinging @McJty

**Comment by radfast** [comment]
This appears to be 100% an RFTools issue fixed in July 2016
https://github.com/McJty/RFTools/issues/572

Not clear why it is thought this is an issue in MicdoodleCore?  See https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md
